package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * CountryMaster generated by hbm2java
 */
public class CountryMaster implements java.io.Serializable {

	private Long countryId;
	private String countryName;
	private Set<StateMaster> stateMasters = new HashSet<StateMaster>(0);

	public CountryMaster() {
	}

	public CountryMaster(String countryName) {
		this.countryName = countryName;
	}

	public CountryMaster(String countryName, Set<StateMaster> stateMasters) {
		this.countryName = countryName;
		this.stateMasters = stateMasters;
	}

	public Long getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public Set<StateMaster> getStateMasters() {
		return this.stateMasters;
	}

	public void setStateMasters(Set<StateMaster> stateMasters) {
		this.stateMasters = stateMasters;
	}

}
