package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FoulMaster generated by hbm2java
 */
public class FoulMaster implements java.io.Serializable {

	private Long foulId;
	private String foulName;
	private String foulDescription;
	private Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters = new HashSet<TournamentMatchFoulMaster>(0);

	public FoulMaster() {
	}

	public FoulMaster(String foulName, String foulDescription) {
		this.foulName = foulName;
		this.foulDescription = foulDescription;
	}

	public FoulMaster(String foulName, String foulDescription,
			Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters) {
		this.foulName = foulName;
		this.foulDescription = foulDescription;
		this.tournamentMatchFoulMasters = tournamentMatchFoulMasters;
	}

	public Long getFoulId() {
		return this.foulId;
	}

	public void setFoulId(Long foulId) {
		this.foulId = foulId;
	}

	public String getFoulName() {
		return this.foulName;
	}

	public void setFoulName(String foulName) {
		this.foulName = foulName;
	}

	public String getFoulDescription() {
		return this.foulDescription;
	}

	public void setFoulDescription(String foulDescription) {
		this.foulDescription = foulDescription;
	}

	public Set<TournamentMatchFoulMaster> getTournamentMatchFoulMasters() {
		return this.tournamentMatchFoulMasters;
	}

	public void setTournamentMatchFoulMasters(Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters) {
		this.tournamentMatchFoulMasters = tournamentMatchFoulMasters;
	}

}
