package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupMaster generated by hbm2java
 */
public class GroupMaster implements java.io.Serializable {

	private Long groupId;
	private String groupName;
	private Set<TournamentGroupDetailsMaster> tournamentGroupDetailsMasters = new HashSet<TournamentGroupDetailsMaster>(
			0);

	public GroupMaster() {
	}

	public GroupMaster(String groupName) {
		this.groupName = groupName;
	}

	public GroupMaster(String groupName, Set<TournamentGroupDetailsMaster> tournamentGroupDetailsMasters) {
		this.groupName = groupName;
		this.tournamentGroupDetailsMasters = tournamentGroupDetailsMasters;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set<TournamentGroupDetailsMaster> getTournamentGroupDetailsMasters() {
		return this.tournamentGroupDetailsMasters;
	}

	public void setTournamentGroupDetailsMasters(Set<TournamentGroupDetailsMaster> tournamentGroupDetailsMasters) {
		this.tournamentGroupDetailsMasters = tournamentGroupDetailsMasters;
	}

}
