package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MajorSkill generated by hbm2java
 */
public class MajorSkill implements java.io.Serializable {

	private Long majorSkillId;
	private String skillName;
	private Set<PlayerProfileMaster> playerProfileMasters = new HashSet<PlayerProfileMaster>(0);

	public MajorSkill() {
	}

	public MajorSkill(String skillName) {
		this.skillName = skillName;
	}

	public MajorSkill(String skillName, Set<PlayerProfileMaster> playerProfileMasters) {
		this.skillName = skillName;
		this.playerProfileMasters = playerProfileMasters;
	}

	public Long getMajorSkillId() {
		return this.majorSkillId;
	}

	public void setMajorSkillId(Long majorSkillId) {
		this.majorSkillId = majorSkillId;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public Set<PlayerProfileMaster> getPlayerProfileMasters() {
		return this.playerProfileMasters;
	}

	public void setPlayerProfileMasters(Set<PlayerProfileMaster> playerProfileMasters) {
		this.playerProfileMasters = playerProfileMasters;
	}

}
