package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * MatchPointMaster generated by hbm2java
 */
public class MatchPointMaster implements java.io.Serializable {

	private Long matchPointId;
	private SymbolMaster symbolMaster;
	private TournamentMatchMaster tournamentMatchMaster;
	private TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkDefenceId;
	private TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAttackerId;
	private TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAssistId;
	private long inningNumber;
	private long turnNumber;
	private Date runTime;
	private Date perTime;

	public MatchPointMaster() {
	}

	public MatchPointMaster(SymbolMaster symbolMaster, TournamentMatchMaster tournamentMatchMaster,
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkDefenceId,
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAttackerId,
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAssistId, long inningNumber,
			long turnNumber, Date runTime, Date perTime) {
		this.symbolMaster = symbolMaster;
		this.tournamentMatchMaster = tournamentMatchMaster;
		this.tournamentParticipantTeamMasterByFkDefenceId = tournamentParticipantTeamMasterByFkDefenceId;
		this.tournamentParticipantTeamMasterByFkAttackerId = tournamentParticipantTeamMasterByFkAttackerId;
		this.tournamentParticipantTeamMasterByFkAssistId = tournamentParticipantTeamMasterByFkAssistId;
		this.inningNumber = inningNumber;
		this.turnNumber = turnNumber;
		this.runTime = runTime;
		this.perTime = perTime;
	}

	public Long getMatchPointId() {
		return this.matchPointId;
	}

	public void setMatchPointId(Long matchPointId) {
		this.matchPointId = matchPointId;
	}

	public SymbolMaster getSymbolMaster() {
		return this.symbolMaster;
	}

	public void setSymbolMaster(SymbolMaster symbolMaster) {
		this.symbolMaster = symbolMaster;
	}

	public TournamentMatchMaster getTournamentMatchMaster() {
		return this.tournamentMatchMaster;
	}

	public void setTournamentMatchMaster(TournamentMatchMaster tournamentMatchMaster) {
		this.tournamentMatchMaster = tournamentMatchMaster;
	}

	public TournamentParticipantTeamMaster getTournamentParticipantTeamMasterByFkDefenceId() {
		return this.tournamentParticipantTeamMasterByFkDefenceId;
	}

	public void setTournamentParticipantTeamMasterByFkDefenceId(
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkDefenceId) {
		this.tournamentParticipantTeamMasterByFkDefenceId = tournamentParticipantTeamMasterByFkDefenceId;
	}

	public TournamentParticipantTeamMaster getTournamentParticipantTeamMasterByFkAttackerId() {
		return this.tournamentParticipantTeamMasterByFkAttackerId;
	}

	public void setTournamentParticipantTeamMasterByFkAttackerId(
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAttackerId) {
		this.tournamentParticipantTeamMasterByFkAttackerId = tournamentParticipantTeamMasterByFkAttackerId;
	}

	public TournamentParticipantTeamMaster getTournamentParticipantTeamMasterByFkAssistId() {
		return this.tournamentParticipantTeamMasterByFkAssistId;
	}

	public void setTournamentParticipantTeamMasterByFkAssistId(
			TournamentParticipantTeamMaster tournamentParticipantTeamMasterByFkAssistId) {
		this.tournamentParticipantTeamMasterByFkAssistId = tournamentParticipantTeamMasterByFkAssistId;
	}

	public long getInningNumber() {
		return this.inningNumber;
	}

	public void setInningNumber(long inningNumber) {
		this.inningNumber = inningNumber;
	}

	public long getTurnNumber() {
		return this.turnNumber;
	}

	public void setTurnNumber(long turnNumber) {
		this.turnNumber = turnNumber;
	}

	public Date getRunTime() {
		return this.runTime;
	}

	public void setRunTime(Date runTime) {
		this.runTime = runTime;
	}

	public Date getPerTime() {
		return this.perTime;
	}

	public void setPerTime(Date perTime) {
		this.perTime = perTime;
	}

}
