package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlayerProfileMaster generated by hbm2java
 */
public class PlayerProfileMaster implements java.io.Serializable {

	private Long playerProfileId;
	private CityMaster cityMaster;
	private MajorSkill majorSkill;
	private RoleMaster roleMaster;
	private TeamMaster teamMaster;
	private String name;
	private Date dateOfBirth;
	private byte[] photo;
	private String height;
	private Double weight;
	private Integer totalToursParticipated;
	private String achievements;
	private String gender;
	private String contact;
	private Set<TournamentParticipantTeamMaster> tournamentParticipantTeamMasters = new HashSet<TournamentParticipantTeamMaster>(
			0);

	public PlayerProfileMaster() {
	}

	public PlayerProfileMaster(CityMaster cityMaster, TeamMaster teamMaster, String name, Date dateOfBirth,
			String gender, String contact) {
		this.cityMaster = cityMaster;
		this.teamMaster = teamMaster;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.contact = contact;
	}

	public PlayerProfileMaster(CityMaster cityMaster, MajorSkill majorSkill, RoleMaster roleMaster,
			TeamMaster teamMaster, String name, Date dateOfBirth, byte[] photo, String height, Double weight,
			Integer totalToursParticipated, String achievements, String gender, String contact,
			Set<TournamentParticipantTeamMaster> tournamentParticipantTeamMasters) {
		this.cityMaster = cityMaster;
		this.majorSkill = majorSkill;
		this.roleMaster = roleMaster;
		this.teamMaster = teamMaster;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.photo = photo;
		this.height = height;
		this.weight = weight;
		this.totalToursParticipated = totalToursParticipated;
		this.achievements = achievements;
		this.gender = gender;
		this.contact = contact;
		this.tournamentParticipantTeamMasters = tournamentParticipantTeamMasters;
	}

	public Long getPlayerProfileId() {
		return this.playerProfileId;
	}

	public void setPlayerProfileId(Long playerProfileId) {
		this.playerProfileId = playerProfileId;
	}

	public CityMaster getCityMaster() {
		return this.cityMaster;
	}

	public void setCityMaster(CityMaster cityMaster) {
		this.cityMaster = cityMaster;
	}

	public MajorSkill getMajorSkill() {
		return this.majorSkill;
	}

	public void setMajorSkill(MajorSkill majorSkill) {
		this.majorSkill = majorSkill;
	}

	public RoleMaster getRoleMaster() {
		return this.roleMaster;
	}

	public void setRoleMaster(RoleMaster roleMaster) {
		this.roleMaster = roleMaster;
	}

	public TeamMaster getTeamMaster() {
		return this.teamMaster;
	}

	public void setTeamMaster(TeamMaster teamMaster) {
		this.teamMaster = teamMaster;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public Integer getTotalToursParticipated() {
		return this.totalToursParticipated;
	}

	public void setTotalToursParticipated(Integer totalToursParticipated) {
		this.totalToursParticipated = totalToursParticipated;
	}

	public String getAchievements() {
		return this.achievements;
	}

	public void setAchievements(String achievements) {
		this.achievements = achievements;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Set<TournamentParticipantTeamMaster> getTournamentParticipantTeamMasters() {
		return this.tournamentParticipantTeamMasters;
	}

	public void setTournamentParticipantTeamMasters(
			Set<TournamentParticipantTeamMaster> tournamentParticipantTeamMasters) {
		this.tournamentParticipantTeamMasters = tournamentParticipantTeamMasters;
	}

}
