package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * StateMaster generated by hbm2java
 */
public class StateMaster implements java.io.Serializable {

	private Long stateId;
	private CountryMaster countryMaster;
	private String stateName;
	private Set<CityMaster> cityMasters = new HashSet<CityMaster>(0);

	public StateMaster() {
	}

	public StateMaster(CountryMaster countryMaster, String stateName) {
		this.countryMaster = countryMaster;
		this.stateName = stateName;
	}

	public StateMaster(CountryMaster countryMaster, String stateName, Set<CityMaster> cityMasters) {
		this.countryMaster = countryMaster;
		this.stateName = stateName;
		this.cityMasters = cityMasters;
	}

	public Long getStateId() {
		return this.stateId;
	}

	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	public CountryMaster getCountryMaster() {
		return this.countryMaster;
	}

	public void setCountryMaster(CountryMaster countryMaster) {
		this.countryMaster = countryMaster;
	}

	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public Set<CityMaster> getCityMasters() {
		return this.cityMasters;
	}

	public void setCityMasters(Set<CityMaster> cityMasters) {
		this.cityMasters = cityMasters;
	}

}
