package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SymbolMaster generated by hbm2java
 */
public class SymbolMaster implements java.io.Serializable {

	private Long symbolId;
	private String description;
	private Set<MatchPointMaster> matchPointMasters = new HashSet<MatchPointMaster>(0);

	public SymbolMaster() {
	}

	public SymbolMaster(String description) {
		this.description = description;
	}

	public SymbolMaster(String description, Set<MatchPointMaster> matchPointMasters) {
		this.description = description;
		this.matchPointMasters = matchPointMasters;
	}

	public Long getSymbolId() {
		return this.symbolId;
	}

	public void setSymbolId(Long symbolId) {
		this.symbolId = symbolId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<MatchPointMaster> getMatchPointMasters() {
		return this.matchPointMasters;
	}

	public void setMatchPointMasters(Set<MatchPointMaster> matchPointMasters) {
		this.matchPointMasters = matchPointMasters;
	}

}
