package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

/**
 * TossDetailsMaster generated by hbm2java
 */
public class TossDetailsMaster implements java.io.Serializable {

	private Long tossDetailsId;
	private TournamentMatchMaster tournamentMatchMaster;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private String electedTo;

	public TossDetailsMaster() {
	}

	public TossDetailsMaster(TournamentMatchMaster tournamentMatchMaster,
			TournamentParticipantMaster tournamentParticipantMaster, String electedTo) {
		this.tournamentMatchMaster = tournamentMatchMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.electedTo = electedTo;
	}

	public Long getTossDetailsId() {
		return this.tossDetailsId;
	}

	public void setTossDetailsId(Long tossDetailsId) {
		this.tossDetailsId = tossDetailsId;
	}

	public TournamentMatchMaster getTournamentMatchMaster() {
		return this.tournamentMatchMaster;
	}

	public void setTournamentMatchMaster(TournamentMatchMaster tournamentMatchMaster) {
		this.tournamentMatchMaster = tournamentMatchMaster;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public String getElectedTo() {
		return this.electedTo;
	}

	public void setElectedTo(String electedTo) {
		this.electedTo = electedTo;
	}

}
