package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

/**
 * TournamentGroupDetailsMaster generated by hbm2java
 */
public class TournamentGroupDetailsMaster implements java.io.Serializable {

	private Long tourGroupId;
	private GroupMaster groupMaster;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private String groupType;

	public TournamentGroupDetailsMaster() {
	}

	public TournamentGroupDetailsMaster(GroupMaster groupMaster,
			TournamentParticipantMaster tournamentParticipantMaster, String groupType) {
		this.groupMaster = groupMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.groupType = groupType;
	}

	public Long getTourGroupId() {
		return this.tourGroupId;
	}

	public void setTourGroupId(Long tourGroupId) {
		this.tourGroupId = tourGroupId;
	}

	public GroupMaster getGroupMaster() {
		return this.groupMaster;
	}

	public void setGroupMaster(GroupMaster groupMaster) {
		this.groupMaster = groupMaster;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public String getGroupType() {
		return this.groupType;
	}

	public void setGroupType(String groupType) {
		this.groupType = groupType;
	}

}
