package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TournamentMatchResultMaster generated by hbm2java
 */
public class TournamentMatchResultMaster implements java.io.Serializable {

	private Long matchResultId;
	private TournamentMatchMaster tournamentMatchMaster;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private TournamentParticipantTeamMaster tournamentParticipantTeamMaster;
	private long wonByPoints;
	private Date wonByTime;
	private String resultDetails;

	public TournamentMatchResultMaster() {
	}

	public TournamentMatchResultMaster(TournamentMatchMaster tournamentMatchMaster,
			TournamentParticipantTeamMaster tournamentParticipantTeamMaster, long wonByPoints, Date wonByTime,
			String resultDetails) {
		this.tournamentMatchMaster = tournamentMatchMaster;
		this.tournamentParticipantTeamMaster = tournamentParticipantTeamMaster;
		this.wonByPoints = wonByPoints;
		this.wonByTime = wonByTime;
		this.resultDetails = resultDetails;
	}

	public TournamentMatchResultMaster(TournamentMatchMaster tournamentMatchMaster,
			TournamentParticipantMaster tournamentParticipantMaster,
			TournamentParticipantTeamMaster tournamentParticipantTeamMaster, long wonByPoints, Date wonByTime,
			String resultDetails) {
		this.tournamentMatchMaster = tournamentMatchMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.tournamentParticipantTeamMaster = tournamentParticipantTeamMaster;
		this.wonByPoints = wonByPoints;
		this.wonByTime = wonByTime;
		this.resultDetails = resultDetails;
	}

	public Long getMatchResultId() {
		return this.matchResultId;
	}

	public void setMatchResultId(Long matchResultId) {
		this.matchResultId = matchResultId;
	}

	public TournamentMatchMaster getTournamentMatchMaster() {
		return this.tournamentMatchMaster;
	}

	public void setTournamentMatchMaster(TournamentMatchMaster tournamentMatchMaster) {
		this.tournamentMatchMaster = tournamentMatchMaster;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public TournamentParticipantTeamMaster getTournamentParticipantTeamMaster() {
		return this.tournamentParticipantTeamMaster;
	}

	public void setTournamentParticipantTeamMaster(TournamentParticipantTeamMaster tournamentParticipantTeamMaster) {
		this.tournamentParticipantTeamMaster = tournamentParticipantTeamMaster;
	}

	public long getWonByPoints() {
		return this.wonByPoints;
	}

	public void setWonByPoints(long wonByPoints) {
		this.wonByPoints = wonByPoints;
	}

	public Date getWonByTime() {
		return this.wonByTime;
	}

	public void setWonByTime(Date wonByTime) {
		this.wonByTime = wonByTime;
	}

	public String getResultDetails() {
		return this.resultDetails;
	}

	public void setResultDetails(String resultDetails) {
		this.resultDetails = resultDetails;
	}

}
