package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TournamentMatchMaster generated by hbm2java
 */
public class TournamentMatchMaster implements java.io.Serializable {

	private Long tournamentMatchId;
	private OfficialMaster officialMasterByFkMatchRefree;
	private OfficialMaster officialMasterByFkUmpire2;
	private OfficialMaster officialMasterByFkUmpire1;
	private OfficialMaster officialMasterByFkScorer2;
	private OfficialMaster officialMasterByFkScorer1;
	private TournamentParticipantMaster tournamentParticipantMasterByFkTeam2Id;
	private TournamentParticipantMaster tournamentParticipantMasterByFkTeam1Id;
	private TournamentScheduleMaster tournamentScheduleMaster;
	private long matchNumber;
	private String matchDetails;
	private Set<MatchPointMaster> matchPointMasters = new HashSet<MatchPointMaster>(0);
	private Set<TossDetailsMaster> tossDetailsMasters = new HashSet<TossDetailsMaster>(0);
	private Set<TournamentScheduleMaster> tournamentScheduleMasters = new HashSet<TournamentScheduleMaster>(0);
	private Set<TournamentMatchResultMaster> tournamentMatchResultMasters = new HashSet<TournamentMatchResultMaster>(0);
	private Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters = new HashSet<TournamentMatchFoulMaster>(0);

	public TournamentMatchMaster() {
	}

	public TournamentMatchMaster(OfficialMaster officialMasterByFkMatchRefree, OfficialMaster officialMasterByFkUmpire2,
			OfficialMaster officialMasterByFkUmpire1, OfficialMaster officialMasterByFkScorer2,
			OfficialMaster officialMasterByFkScorer1,
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam2Id,
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam1Id,
			TournamentScheduleMaster tournamentScheduleMaster, long matchNumber, String matchDetails) {
		this.officialMasterByFkMatchRefree = officialMasterByFkMatchRefree;
		this.officialMasterByFkUmpire2 = officialMasterByFkUmpire2;
		this.officialMasterByFkUmpire1 = officialMasterByFkUmpire1;
		this.officialMasterByFkScorer2 = officialMasterByFkScorer2;
		this.officialMasterByFkScorer1 = officialMasterByFkScorer1;
		this.tournamentParticipantMasterByFkTeam2Id = tournamentParticipantMasterByFkTeam2Id;
		this.tournamentParticipantMasterByFkTeam1Id = tournamentParticipantMasterByFkTeam1Id;
		this.tournamentScheduleMaster = tournamentScheduleMaster;
		this.matchNumber = matchNumber;
		this.matchDetails = matchDetails;
	}

	public TournamentMatchMaster(OfficialMaster officialMasterByFkMatchRefree, OfficialMaster officialMasterByFkUmpire2,
			OfficialMaster officialMasterByFkUmpire1, OfficialMaster officialMasterByFkScorer2,
			OfficialMaster officialMasterByFkScorer1,
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam2Id,
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam1Id,
			TournamentScheduleMaster tournamentScheduleMaster, long matchNumber, String matchDetails,
			Set<MatchPointMaster> matchPointMasters, Set<TossDetailsMaster> tossDetailsMasters,
			Set<TournamentScheduleMaster> tournamentScheduleMasters,
			Set<TournamentMatchResultMaster> tournamentMatchResultMasters,
			Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters) {
		this.officialMasterByFkMatchRefree = officialMasterByFkMatchRefree;
		this.officialMasterByFkUmpire2 = officialMasterByFkUmpire2;
		this.officialMasterByFkUmpire1 = officialMasterByFkUmpire1;
		this.officialMasterByFkScorer2 = officialMasterByFkScorer2;
		this.officialMasterByFkScorer1 = officialMasterByFkScorer1;
		this.tournamentParticipantMasterByFkTeam2Id = tournamentParticipantMasterByFkTeam2Id;
		this.tournamentParticipantMasterByFkTeam1Id = tournamentParticipantMasterByFkTeam1Id;
		this.tournamentScheduleMaster = tournamentScheduleMaster;
		this.matchNumber = matchNumber;
		this.matchDetails = matchDetails;
		this.matchPointMasters = matchPointMasters;
		this.tossDetailsMasters = tossDetailsMasters;
		this.tournamentScheduleMasters = tournamentScheduleMasters;
		this.tournamentMatchResultMasters = tournamentMatchResultMasters;
		this.tournamentMatchFoulMasters = tournamentMatchFoulMasters;
	}

	public Long getTournamentMatchId() {
		return this.tournamentMatchId;
	}

	public void setTournamentMatchId(Long tournamentMatchId) {
		this.tournamentMatchId = tournamentMatchId;
	}

	public OfficialMaster getOfficialMasterByFkMatchRefree() {
		return this.officialMasterByFkMatchRefree;
	}

	public void setOfficialMasterByFkMatchRefree(OfficialMaster officialMasterByFkMatchRefree) {
		this.officialMasterByFkMatchRefree = officialMasterByFkMatchRefree;
	}

	public OfficialMaster getOfficialMasterByFkUmpire2() {
		return this.officialMasterByFkUmpire2;
	}

	public void setOfficialMasterByFkUmpire2(OfficialMaster officialMasterByFkUmpire2) {
		this.officialMasterByFkUmpire2 = officialMasterByFkUmpire2;
	}

	public OfficialMaster getOfficialMasterByFkUmpire1() {
		return this.officialMasterByFkUmpire1;
	}

	public void setOfficialMasterByFkUmpire1(OfficialMaster officialMasterByFkUmpire1) {
		this.officialMasterByFkUmpire1 = officialMasterByFkUmpire1;
	}

	public OfficialMaster getOfficialMasterByFkScorer2() {
		return this.officialMasterByFkScorer2;
	}

	public void setOfficialMasterByFkScorer2(OfficialMaster officialMasterByFkScorer2) {
		this.officialMasterByFkScorer2 = officialMasterByFkScorer2;
	}

	public OfficialMaster getOfficialMasterByFkScorer1() {
		return this.officialMasterByFkScorer1;
	}

	public void setOfficialMasterByFkScorer1(OfficialMaster officialMasterByFkScorer1) {
		this.officialMasterByFkScorer1 = officialMasterByFkScorer1;
	}

	public TournamentParticipantMaster getTournamentParticipantMasterByFkTeam2Id() {
		return this.tournamentParticipantMasterByFkTeam2Id;
	}

	public void setTournamentParticipantMasterByFkTeam2Id(
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam2Id) {
		this.tournamentParticipantMasterByFkTeam2Id = tournamentParticipantMasterByFkTeam2Id;
	}

	public TournamentParticipantMaster getTournamentParticipantMasterByFkTeam1Id() {
		return this.tournamentParticipantMasterByFkTeam1Id;
	}

	public void setTournamentParticipantMasterByFkTeam1Id(
			TournamentParticipantMaster tournamentParticipantMasterByFkTeam1Id) {
		this.tournamentParticipantMasterByFkTeam1Id = tournamentParticipantMasterByFkTeam1Id;
	}

	public TournamentScheduleMaster getTournamentScheduleMaster() {
		return this.tournamentScheduleMaster;
	}

	public void setTournamentScheduleMaster(TournamentScheduleMaster tournamentScheduleMaster) {
		this.tournamentScheduleMaster = tournamentScheduleMaster;
	}

	public long getMatchNumber() {
		return this.matchNumber;
	}

	public void setMatchNumber(long matchNumber) {
		this.matchNumber = matchNumber;
	}

	public String getMatchDetails() {
		return this.matchDetails;
	}

	public void setMatchDetails(String matchDetails) {
		this.matchDetails = matchDetails;
	}

	public Set<MatchPointMaster> getMatchPointMasters() {
		return this.matchPointMasters;
	}

	public void setMatchPointMasters(Set<MatchPointMaster> matchPointMasters) {
		this.matchPointMasters = matchPointMasters;
	}

	public Set<TossDetailsMaster> getTossDetailsMasters() {
		return this.tossDetailsMasters;
	}

	public void setTossDetailsMasters(Set<TossDetailsMaster> tossDetailsMasters) {
		this.tossDetailsMasters = tossDetailsMasters;
	}

	public Set<TournamentScheduleMaster> getTournamentScheduleMasters() {
		return this.tournamentScheduleMasters;
	}

	public void setTournamentScheduleMasters(Set<TournamentScheduleMaster> tournamentScheduleMasters) {
		this.tournamentScheduleMasters = tournamentScheduleMasters;
	}

	public Set<TournamentMatchResultMaster> getTournamentMatchResultMasters() {
		return this.tournamentMatchResultMasters;
	}

	public void setTournamentMatchResultMasters(Set<TournamentMatchResultMaster> tournamentMatchResultMasters) {
		this.tournamentMatchResultMasters = tournamentMatchResultMasters;
	}

	public Set<TournamentMatchFoulMaster> getTournamentMatchFoulMasters() {
		return this.tournamentMatchFoulMasters;
	}

	public void setTournamentMatchFoulMasters(Set<TournamentMatchFoulMaster> tournamentMatchFoulMasters) {
		this.tournamentMatchFoulMasters = tournamentMatchFoulMasters;
	}

}
