package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TournamentParticipantTeamMaster generated by hbm2java
 */
public class TournamentParticipantTeamMaster implements java.io.Serializable {

	private Long tourPTId;
	private PlayerProfileMaster playerProfileMaster;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private long playerChaseNumber;
	private Set<TournamentMatchResultMaster> tournamentMatchResultMasters = new HashSet<TournamentMatchResultMaster>(0);
	private Set<MatchPointMaster> matchPointMastersForFkDefenceId = new HashSet<MatchPointMaster>(0);
	private Set<MatchPointMaster> matchPointMastersForFkAttackerId = new HashSet<MatchPointMaster>(0);
	private Set<MatchPointMaster> matchPointMastersForFkAssistId = new HashSet<MatchPointMaster>(0);

	public TournamentParticipantTeamMaster() {
	}

	public TournamentParticipantTeamMaster(PlayerProfileMaster playerProfileMaster,
			TournamentParticipantMaster tournamentParticipantMaster, long playerChaseNumber) {
		this.playerProfileMaster = playerProfileMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.playerChaseNumber = playerChaseNumber;
	}

	public TournamentParticipantTeamMaster(PlayerProfileMaster playerProfileMaster,
			TournamentParticipantMaster tournamentParticipantMaster, long playerChaseNumber,
			Set<TournamentMatchResultMaster> tournamentMatchResultMasters,
			Set<MatchPointMaster> matchPointMastersForFkDefenceId,
			Set<MatchPointMaster> matchPointMastersForFkAttackerId,
			Set<MatchPointMaster> matchPointMastersForFkAssistId) {
		this.playerProfileMaster = playerProfileMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.playerChaseNumber = playerChaseNumber;
		this.tournamentMatchResultMasters = tournamentMatchResultMasters;
		this.matchPointMastersForFkDefenceId = matchPointMastersForFkDefenceId;
		this.matchPointMastersForFkAttackerId = matchPointMastersForFkAttackerId;
		this.matchPointMastersForFkAssistId = matchPointMastersForFkAssistId;
	}

	public Long getTourPTId() {
		return this.tourPTId;
	}

	public void setTourPTId(Long tourPTId) {
		this.tourPTId = tourPTId;
	}

	public PlayerProfileMaster getPlayerProfileMaster() {
		return this.playerProfileMaster;
	}

	public void setPlayerProfileMaster(PlayerProfileMaster playerProfileMaster) {
		this.playerProfileMaster = playerProfileMaster;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public long getPlayerChaseNumber() {
		return this.playerChaseNumber;
	}

	public void setPlayerChaseNumber(long playerChaseNumber) {
		this.playerChaseNumber = playerChaseNumber;
	}

	public Set<TournamentMatchResultMaster> getTournamentMatchResultMasters() {
		return this.tournamentMatchResultMasters;
	}

	public void setTournamentMatchResultMasters(Set<TournamentMatchResultMaster> tournamentMatchResultMasters) {
		this.tournamentMatchResultMasters = tournamentMatchResultMasters;
	}

	public Set<MatchPointMaster> getMatchPointMastersForFkDefenceId() {
		return this.matchPointMastersForFkDefenceId;
	}

	public void setMatchPointMastersForFkDefenceId(Set<MatchPointMaster> matchPointMastersForFkDefenceId) {
		this.matchPointMastersForFkDefenceId = matchPointMastersForFkDefenceId;
	}

	public Set<MatchPointMaster> getMatchPointMastersForFkAttackerId() {
		return this.matchPointMastersForFkAttackerId;
	}

	public void setMatchPointMastersForFkAttackerId(Set<MatchPointMaster> matchPointMastersForFkAttackerId) {
		this.matchPointMastersForFkAttackerId = matchPointMastersForFkAttackerId;
	}

	public Set<MatchPointMaster> getMatchPointMastersForFkAssistId() {
		return this.matchPointMastersForFkAssistId;
	}

	public void setMatchPointMastersForFkAssistId(Set<MatchPointMaster> matchPointMastersForFkAssistId) {
		this.matchPointMastersForFkAssistId = matchPointMastersForFkAssistId;
	}

}
