package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TournamentMaster generated by hbm2java
 */
public class TournamentMaster implements java.io.Serializable {

	private Long tournamentId;
	private String name;
	private String description;
	private String location;
	private double prize;
	private String otherDetails;
	private String tourType;
	private String tourStatus;
	private Date tournamentStartDate;
	private Date tournamentEndDate;
	private Date createdDate;
	private String ageGroup;
	private Set<TournamentScheduleDateMaster> tournamentScheduleDateMasters = new HashSet<TournamentScheduleDateMaster>(
			0);
	private Set<TournamentParticipantMaster> tournamentParticipantMasters = new HashSet<TournamentParticipantMaster>(0);

	public TournamentMaster() {
	}

	public TournamentMaster(String name, String description, String location, double prize, String otherDetails,
			String tourType, String tourStatus, Date tournamentStartDate, Date tournamentEndDate, Date createdDate,
			String ageGroup) {
		this.name = name;
		this.description = description;
		this.location = location;
		this.prize = prize;
		this.otherDetails = otherDetails;
		this.tourType = tourType;
		this.tourStatus = tourStatus;
		this.tournamentStartDate = tournamentStartDate;
		this.tournamentEndDate = tournamentEndDate;
		this.createdDate = createdDate;
		this.ageGroup = ageGroup;
	}

	public TournamentMaster(String name, String description, String location, double prize, String otherDetails,
			String tourType, String tourStatus, Date tournamentStartDate, Date tournamentEndDate, Date createdDate,
			String ageGroup, Set<TournamentScheduleDateMaster> tournamentScheduleDateMasters,
			Set<TournamentParticipantMaster> tournamentParticipantMasters) {
		this.name = name;
		this.description = description;
		this.location = location;
		this.prize = prize;
		this.otherDetails = otherDetails;
		this.tourType = tourType;
		this.tourStatus = tourStatus;
		this.tournamentStartDate = tournamentStartDate;
		this.tournamentEndDate = tournamentEndDate;
		this.createdDate = createdDate;
		this.ageGroup = ageGroup;
		this.tournamentScheduleDateMasters = tournamentScheduleDateMasters;
		this.tournamentParticipantMasters = tournamentParticipantMasters;
	}

	public Long getTournamentId() {
		return this.tournamentId;
	}

	public void setTournamentId(Long tournamentId) {
		this.tournamentId = tournamentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public double getPrize() {
		return this.prize;
	}

	public void setPrize(double prize) {
		this.prize = prize;
	}

	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	public String getTourType() {
		return this.tourType;
	}

	public void setTourType(String tourType) {
		this.tourType = tourType;
	}

	public String getTourStatus() {
		return this.tourStatus;
	}

	public void setTourStatus(String tourStatus) {
		this.tourStatus = tourStatus;
	}

	public Date getTournamentStartDate() {
		return this.tournamentStartDate;
	}

	public void setTournamentStartDate(Date tournamentStartDate) {
		this.tournamentStartDate = tournamentStartDate;
	}

	public Date getTournamentEndDate() {
		return this.tournamentEndDate;
	}

	public void setTournamentEndDate(Date tournamentEndDate) {
		this.tournamentEndDate = tournamentEndDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getAgeGroup() {
		return this.ageGroup;
	}

	public void setAgeGroup(String ageGroup) {
		this.ageGroup = ageGroup;
	}

	public Set<TournamentScheduleDateMaster> getTournamentScheduleDateMasters() {
		return this.tournamentScheduleDateMasters;
	}

	public void setTournamentScheduleDateMasters(Set<TournamentScheduleDateMaster> tournamentScheduleDateMasters) {
		this.tournamentScheduleDateMasters = tournamentScheduleDateMasters;
	}

	public Set<TournamentParticipantMaster> getTournamentParticipantMasters() {
		return this.tournamentParticipantMasters;
	}

	public void setTournamentParticipantMasters(Set<TournamentParticipantMaster> tournamentParticipantMasters) {
		this.tournamentParticipantMasters = tournamentParticipantMasters;
	}

}
