package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

/**
 * TournamentParticipantPointsMaster generated by hbm2java
 */
public class TournamentParticipantPointsMaster implements java.io.Serializable {

	private Long tourPartipantPointId;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private long matchesWon;
	private long matchesLost;
	private long matchesDrawn;
	private long totalWickets;
	private long totalPoints;

	public TournamentParticipantPointsMaster() {
	}

	public TournamentParticipantPointsMaster(TournamentParticipantMaster tournamentParticipantMaster, long matchesWon,
			long matchesLost, long matchesDrawn, long totalWickets, long totalPoints) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.matchesWon = matchesWon;
		this.matchesLost = matchesLost;
		this.matchesDrawn = matchesDrawn;
		this.totalWickets = totalWickets;
		this.totalPoints = totalPoints;
	}

	public Long getTourPartipantPointId() {
		return this.tourPartipantPointId;
	}

	public void setTourPartipantPointId(Long tourPartipantPointId) {
		this.tourPartipantPointId = tourPartipantPointId;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public long getMatchesWon() {
		return this.matchesWon;
	}

	public void setMatchesWon(long matchesWon) {
		this.matchesWon = matchesWon;
	}

	public long getMatchesLost() {
		return this.matchesLost;
	}

	public void setMatchesLost(long matchesLost) {
		this.matchesLost = matchesLost;
	}

	public long getMatchesDrawn() {
		return this.matchesDrawn;
	}

	public void setMatchesDrawn(long matchesDrawn) {
		this.matchesDrawn = matchesDrawn;
	}

	public long getTotalWickets() {
		return this.totalWickets;
	}

	public void setTotalWickets(long totalWickets) {
		this.totalWickets = totalWickets;
	}

	public long getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(long totalPoints) {
		this.totalPoints = totalPoints;
	}

}
