package com.digitour.app.model;
// Generated 19 Sep, 2015 10:42:06 PM by Hibernate Tools 4.3.1

/**
 * TournamentMatchFoulMaster generated by hbm2java
 */
public class TournamentMatchFoulMaster implements java.io.Serializable {

	private Long matchFoulId;
	private FoulMaster foulMaster;
	private TournamentMatchMaster tournamentMatchMaster;
	private TournamentParticipantMaster tournamentParticipantMaster;
	private long turnNumber;

	public TournamentMatchFoulMaster() {
	}

	public TournamentMatchFoulMaster(FoulMaster foulMaster, TournamentMatchMaster tournamentMatchMaster,
			TournamentParticipantMaster tournamentParticipantMaster, long turnNumber) {
		this.foulMaster = foulMaster;
		this.tournamentMatchMaster = tournamentMatchMaster;
		this.tournamentParticipantMaster = tournamentParticipantMaster;
		this.turnNumber = turnNumber;
	}

	public Long getMatchFoulId() {
		return this.matchFoulId;
	}

	public void setMatchFoulId(Long matchFoulId) {
		this.matchFoulId = matchFoulId;
	}

	public FoulMaster getFoulMaster() {
		return this.foulMaster;
	}

	public void setFoulMaster(FoulMaster foulMaster) {
		this.foulMaster = foulMaster;
	}

	public TournamentMatchMaster getTournamentMatchMaster() {
		return this.tournamentMatchMaster;
	}

	public void setTournamentMatchMaster(TournamentMatchMaster tournamentMatchMaster) {
		this.tournamentMatchMaster = tournamentMatchMaster;
	}

	public TournamentParticipantMaster getTournamentParticipantMaster() {
		return this.tournamentParticipantMaster;
	}

	public void setTournamentParticipantMaster(TournamentParticipantMaster tournamentParticipantMaster) {
		this.tournamentParticipantMaster = tournamentParticipantMaster;
	}

	public long getTurnNumber() {
		return this.turnNumber;
	}

	public void setTurnNumber(long turnNumber) {
		this.turnNumber = turnNumber;
	}

}
